name: mariadb CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
       mariadb:
          image: mariadb
          env:
              MARIADB_ROOT_PASSWORD: testpass

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y mariadb-client
    - run: mysql -h 127.0.0.1 -u root -p testpass < test.sql
